OnlineQuizPlatform/OnlineQuizPlatform/main/urls.py
from django.urls import path

from OnlineQuizPlatform.main.views.categories import CreateCategoryView, CategoriesView, CategoryDetailsView, \
    EditCategoryView, DeleteCategoryView
from OnlineQuizPlatform.main.views.questions import CreateQuestionView, EditQuestionView, DeleteQuestionView
from OnlineQuizPlatform.main.views.quizzes import CreateQuizView, QuizDetailsView, EditQuizView, DeleteQuizView, \
    take_quiz
from OnlineQuizPlatform.main.views.subcategories import CreateSubCategoryView, SubCategoryDetailsView, \
    EditSubCategoryView, DeleteSubCategoryView

urlpatterns = (
    path('categories/', CategoriesView.as_view(), name='categories'),
    path('categories/create/', CreateCategoryView.as_view(), name='create category'),
    path('categories/details/<int:pk>/', CategoryDetailsView.as_view(), name='category details'),
    path('categories/edit/<int:pk>/', EditCategoryView.as_view(), name='edit category'),
    path('categories/delete/<int:pk>/', DeleteCategoryView.as_view(), name='delete category'),

    path('subcategories/create/', CreateSubCategoryView.as_view(), name='create subcategory'),
    path('subcategories/details/<int:pk>/', SubCategoryDetailsView.as_view(), name='subcategory details'),
    path('subcategories/edit/<int:pk>/', EditSubCategoryView.as_view(), name='edit subcategory'),
    path('subcategories/delete/<int:pk>/', DeleteSubCategoryView.as_view(), name='delete subcategory'),

    path('quizzes/create/', CreateQuizView.as_view(), name='create quiz'),
    path('quizzes/details/<int:pk>/', QuizDetailsView.as_view(), name='quiz details'),
    path('quizzes/edit/<int:pk>/', EditQuizView.as_view(), name='edit quiz'),
    path('quizzes/delete/<int:pk>/', DeleteQuizView.as_view(), name='delete quiz'),
    path('quizzes/take/<int:pk>/', take_quiz, name='take quiz'),

    path('questions/create/', CreateQuestionView.as_view(), name='create question'),
    path('questions/edit/<int:pk>/', EditQuestionView.as_view(), name='edit question'),
    path('questions/delete/<int:pk>/', DeleteQuestionView.as_view(), name='delete question'),

)

OnlineQuizPlatform/OnlineQuizPlatform/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name='index.html'), name='index'),
    path('user/', include('OnlineQuizPlatform.auth_app.urls')),
    path('', include('OnlineQuizPlatform.main.urls')),
]

OnlineQuizPlatform/OnlineQuizPlatform/main/models.py
from django.contrib.auth import get_user_model
from django.core.validators import MinLengthValidator, MinValueValidator
from django.db import models

from OnlineQuizPlatform.common.validators import only_letters_validator

UserModel = get_user_model()


class Category(models.Model):
    NAME_MIN_LEN = 3
    NAME_MAX_LEN = 30

    name = models.CharField(
        max_length=NAME_MAX_LEN,
        unique=True,
        validators=(
            MinLengthValidator(NAME_MIN_LEN),
            only_letters_validator,
        )
    )

    picture = models.URLField()

    description = models.TextField(
        null=True,
        blank=True,
    )

    def __str__(self):
        return self.name


class SubCategory(models.Model):
    NAME_MIN_LEN = 3
    NAME_MAX_LEN = 30

    name = models.CharField(
        max_length=NAME_MAX_LEN,
        unique=True,
        validators=(
            MinLengthValidator(NAME_MIN_LEN),
        )
    )

    picture = models.URLField()

    description = models.TextField(
        null=True,
        blank=True,
    )

    category = models.ForeignKey(
        Category,
        on_delete=models.CASCADE,
    )

    def __str__(self):
        return self.name


class Quiz(models.Model):
    TITLE_MIN_LEN = 5
    TITLE_MAX_LEN = 80

    DURATION_MIN_VALUE = 0

    title = models.CharField(
        max_length=TITLE_MAX_LEN,
        unique=True,
        validators=(
            MinLengthValidator(TITLE_MIN_LEN),
        )
    )

    duration = models.IntegerField(
        validators=(
            MinValueValidator(DURATION_MIN_VALUE),
        )
    )

    description = models.TextField(
        null=True,
        blank=True,
    )

    created_on = models.DateTimeField(
        auto_now_add=True,
    )

    subcategory = models.ForeignKey(
        SubCategory,
        on_delete=models.CASCADE,
    )

    author = models.ForeignKey(
        UserModel,
        on_delete=models.CASCADE,
    )

    def __str__(self):
        return self.title


class Question(models.Model):
    DESCRIPTION_MAX_LEN = 150
    OPTIONS_MAX_LEN = 150
    ANSWER_MAX_LEN = 10

    description = models.CharField(
        max_length=DESCRIPTION_MAX_LEN,
    )

    option1 = models.CharField(
        max_length=OPTIONS_MAX_LEN,
    )

    option2 = models.CharField(
        max_length=OPTIONS_MAX_LEN,
    )

    option3 = models.CharField(
        max_length=OPTIONS_MAX_LEN,
    )

    option4 = models.CharField(
        max_length=OPTIONS_MAX_LEN,
    )

    answer = models.CharField(
        max_length=ANSWER_MAX_LEN,
    )

    quiz = models.ForeignKey(
        Quiz,
        on_delete=models.CASCADE,
    )

    def __str__(self):
        return self.description


class QuizResult(models.Model):
    SCORE_DEFAULT_VALUE = 0
    SCORE_MIN_VALUE = 0

    TAKEN_TIME_DEFAULT_VALUE = 0
    TAKEN_TIME_MIN_VALUE = 0

    CORRECT_ANSWERS_DEFAULT_VALUE = 0
    CORRECT_ANSWERS_MIN_VALUE = 0

    INCORRECT_ANSWERS_DEFAULT_VALUE = 0
    INCORRECT_ANSWERS_MIN_VALUE = 0

    score = models.IntegerField(
        default=SCORE_DEFAULT_VALUE,
        validators=(
            MinValueValidator(SCORE_MIN_VALUE),
        )
    )

    taken_time = models.IntegerField(
        default=TAKEN_TIME_DEFAULT_VALUE,
        validators=(
            MinValueValidator(TAKEN_TIME_MIN_VALUE),
        )
    )

    correct_answers = models.IntegerField(
        default=CORRECT_ANSWERS_DEFAULT_VALUE,
        validators=(
            MinValueValidator(CORRECT_ANSWERS_MIN_VALUE),
        )
    )

    incorrect_answers = models.IntegerField(
        default=INCORRECT_ANSWERS_DEFAULT_VALUE,
        validators=(
            MinValueValidator(INCORRECT_ANSWERS_MIN_VALUE),
        )
    )

    first_taken = models.DateTimeField(
        auto_now_add=True,
    )

    last_taken = models.DateTimeField(
        auto_now=True,
    )

    quiz = models.ForeignKey(
        Quiz,
        on_delete=models.CASCADE,
    )

    player = models.ForeignKey(
        UserModel,
        on_delete=models.CASCADE,
    )

    def __str__(self):
        return self.score

OnlineQuizPlatform/OnlineQuizPlatform/main/forms/categories.py
from django import forms

from OnlineQuizPlatform.common.helpers import BootstrapFormMixin
from OnlineQuizPlatform.main.models import Category


class CreateCategoryForm(BootstrapFormMixin, forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._init_bootstrap_form_control()

    class Meta:
        model = Category
        fields = ('name', 'picture', 'description')


class DeleteCategoryForm(forms.ModelForm):
    def save(self, commit=True):
        self.instance.delete()
        return self.instance

    class Meta:
        model = Category
        fields = ()

OnlineQuizPlatform/OnlineQuizPlatform/main/forms/questions.py
from django import forms

from OnlineQuizPlatform.common.helpers import BootstrapFormMixin
from OnlineQuizPlatform.main.models import Question, Quiz


class CreateQuestionForm(BootstrapFormMixin, forms.ModelForm):
    def __init__(self, *args, **kwargs, ):
        super().__init__(*args, **kwargs)
        self._init_bootstrap_form_control()

    class Meta:
        model = Question
        fields = ('description', 'option1', 'option2', 'option3', 'option4', 'answer', 'quiz')


class DeleteQuestionForm(forms.ModelForm):
    def save(self, commit=True):
        self.instance.delete()
        return self.instance

    class Meta:
        model = Question
        fields = ()

OnlineQuizPlatform/OnlineQuizPlatform/main/views/categories.py
from django.contrib.auth import mixins as auth_mixins
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views import generic as views

from OnlineQuizPlatform.main.forms.categories import CreateCategoryForm, DeleteCategoryForm
from OnlineQuizPlatform.main.models import Category, SubCategory


class CreateCategoryView(auth_mixins.LoginRequiredMixin, auth_mixins.PermissionRequiredMixin, views.CreateView):
    template_name = 'main/category_create.html'
    form_class = CreateCategoryForm
    success_url = reverse_lazy('categories')
    permission_required = 'main.add_category'

    def dispatch(self, request, *args, **kwargs):
        if not self.has_permission():
            return redirect('restricted')
        return super().dispatch(request, *args, **kwargs)


class CategoriesView(views.ListView):
    model = Category
    template_name = 'main/categories.html'
    context_object_name = 'categories'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        categories = Category.objects.all().order_by('name')

        context['categories'] = categories

        return context


class CategoryDetailsView(views.DetailView):
    model = Category
    template_name = 'main/category_details.html'
    context_object_name = 'category'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        subcategories = SubCategory.objects.filter(category_id=self.object.id).order_by('name')

        context['subcategories'] = subcategories

        return context


class EditCategoryView(auth_mixins.LoginRequiredMixin, auth_mixins.PermissionRequiredMixin, views.UpdateView):
    model = Category
    fields = ('name', 'picture', 'description')
    template_name = 'main/category_edit.html'
    permission_required = 'main.change_category'

    def dispatch(self, request, *args, **kwargs):
        if not self.has_permission():
            return redirect('restricted')
        return super().dispatch(request, *args, **kwargs)

    def get_success_url(self, **kwargs):
        return reverse_lazy('category details', kwargs={'pk': self.object.id})


class DeleteCategoryView(auth_mixins.LoginRequiredMixin, auth_mixins.PermissionRequiredMixin, views.DeleteView):
    model = Category
    form_class = DeleteCategoryForm
    template_name = 'main/category-delete.html'
    success_url = reverse_lazy('categories')
    permission_required = 'main.delete_category'

    def dispatch(self, request, *args, **kwargs):
        if not self.has_permission():
            return redirect('restricted')
        return super().dispatch(request, *args, **kwargs)

OnlineQuizPlatform/OnlineQuizPlatform/main/views/questions.py
from django.contrib.auth import mixins as auth_mixins
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views import generic as views

from OnlineQuizPlatform.main.forms.questions import CreateQuestionForm, DeleteQuestionForm
from OnlineQuizPlatform.main.models import Question


class CreateQuestionView(auth_mixins.LoginRequiredMixin, auth_mixins.PermissionRequiredMixin, views.CreateView):
    template_name = 'main/question_create.html'
    form_class = CreateQuestionForm
    permission_required = 'main.add_question'

    def dispatch(self, request, *args, **kwargs):
        if not self.has_permission():
            return redirect('restricted')
        return super().dispatch(request, *args, **kwargs)

    def get_success_url(self, **kwargs):
        return reverse_lazy('quiz details', kwargs={'pk': self.object.quiz.id})


class EditQuestionView(auth_mixins.LoginRequiredMixin, auth_mixins.PermissionRequiredMixin, views.UpdateView):
    model = Question
    fields = ('description', 'option1', 'option2', 'option3', 'option4', 'answer')
    template_name = 'main/question_edit.html'
    permission_required = 'main.change_question'

    def dispatch(self, request, *args, **kwargs):
        if not self.has_permission():
            return redirect('restricted')
        return super().dispatch(request, *args, **kwargs)

    def get_success_url(self, **kwargs):
        return reverse_lazy('quiz details', kwargs={'pk': self.object.quiz.id})


class DeleteQuestionView(auth_mixins.LoginRequiredMixin, auth_mixins.PermissionRequiredMixin, views.DeleteView):
    model = Question
    form_class = DeleteQuestionForm
    template_name = 'main/question-delete.html'
    permission_required = 'main.delete_question'

    def dispatch(self, request, *args, **kwargs):
        if not self.has_permission():
            return redirect('restricted')
        return super().dispatch(request, *args, **kwargs)

    def get_success_url(self, **kwargs):
        return reverse_lazy('quiz details', kwargs={'pk': self.object.quiz.id})

OnlineQuizPlatform/OnlineQuizPlatform/main/views/quizzes.py
from django.contrib.auth import mixins as auth_mixins
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views import generic as views

from OnlineQuizPlatform.main.forms.quizzes import CreateQuizForm, DeleteQuizForm
from OnlineQuizPlatform.main.models import Quiz, Question, QuizResult


class CreateQuizView(auth_mixins.LoginRequiredMixin, auth_mixins.PermissionRequiredMixin, views.CreateView):
    template_name = 'main/quiz_create.html'
    form_class = CreateQuizForm
    permission_required = 'main.add_quiz'

    def dispatch(self, request, *args, **kwargs):
        if not self.has_permission():
            return redirect('restricted')
        return super().dispatch(request, *args, **kwargs)

    def get_success_url(self, **kwargs):
        return reverse_lazy('subcategory details', kwargs={'pk': self.object.subcategory.id})

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['author'] = self.request.user
        return kwargs


class QuizDetailsView(views.DetailView):
    model = Quiz
    template_name = 'main/quiz_details.html'
    context_object_name = 'quiz'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        questions = Question.objects.filter(quiz_id=self.object.id)

        context['questions'] = questions

        return context


class EditQuizView(auth_mixins.LoginRequiredMixin, auth_mixins.PermissionRequiredMixin, views.UpdateView):
    model = Quiz
    fields = ('title', 'duration', 'description')
    template_name = 'main/quiz_edit.html'
    permission_required = 'main.change_quiz'

    def dispatch(self, request, *args, **kwargs):
        if not self.has_permission():
            return redirect('restricted')
        return super().dispatch(request, *args, **kwargs)

    def get_success_url(self, **kwargs):
        return reverse_lazy('quiz details', kwargs={'pk': self.object.id})


class DeleteQuizView(auth_mixins.LoginRequiredMixin, auth_mixins.PermissionRequiredMixin, views.DeleteView):
    model = Quiz
    form_class = DeleteQuizForm
    template_name = 'main/quiz-delete.html'
    permission_required = 'main.delete_quiz'

    def dispatch(self, request, *args, **kwargs):
        if not self.has_permission():
            return redirect('restricted')
        return super().dispatch(request, *args, **kwargs)

    def get_success_url(self, **kwargs):
        return reverse_lazy('subcategory details', kwargs={'pk': self.object.subcategory.id})


@login_required
def take_quiz(request, pk):
    quiz = Quiz.objects.get(pk=pk)

    questions = Question.objects.filter(quiz_id=pk)
    try:
        quiz_result = QuizResult.objects.get(quiz=quiz, player=request.user)
    except:
        quiz_result = QuizResult(quiz=quiz, player=request.user)

    if request.method == 'POST':

        score = 0
        correct = 0
        incorrect = 0

        for question in questions:
            if question.answer == request.POST.get(question.description):
                score += 10
                correct += 1
            else:
                incorrect += 1

        taken_time = request.POST.get('timer')

        if score > quiz_result.score:
            quiz_result.score = score
            quiz_result.correct_answers = correct
            quiz_result.incorrect_answers = incorrect
            quiz_result.taken_time = int(taken_time)
            best_result = True
            quiz_result.save()
        elif score == quiz_result.score and int(taken_time) < quiz_result.taken_time:
            quiz_result.score = score
            quiz_result.correct_answers = correct
            quiz_result.incorrect_answers = incorrect
            quiz_result.taken_time = int(taken_time)
            best_result = True
            quiz_result.save()
        else:
            best_result = False

        context = {
            'score': score,
            'correct': correct,
            'incorrect': incorrect,
            'taken_time': taken_time,
            'best_result': best_result,
            'quiz_result': quiz_result,
            'quiz': quiz,
            'player': request.user,
        }
        return render(request, 'main/result.html', context)
    else:
        context = {
            'quiz': quiz,
            'questions': questions,
            'quiz_result': quiz_result,
        }
        return render(request, 'main/take-quiz.html', context)

OnlineQuizPlatform/templates/main/category_create.html
{% extends 'base.html' %}

{% block content %}
    <form class='form' action="{% url 'create category' %}" method="post">
        <h3 class="text-center text-info">Създай категория</h3>
        {% csrf_token %}
        {% for field in form %}
            <div>
                {{ field.label_tag }}
            </div>
            <div>
                {{ field }}
                {{ field.errors }}
            </div>

        {% endfor %}

        <input type="submit" name="submit" class="btn btn-info btn-md" value="Създай">
    </form>
{% endblock %}

OnlineQuizPlatform/templates/main/category_edit.html
{% extends 'base.html' %}

{% block content %}
    <form class='form' action="{% url 'edit category' category.id %}" method="post">
        <h3 class="text-center text-info">Редактирай категория</h3>
        {% csrf_token %}
        {% for field in form %}
            <div>
                {{ field.label_tag }}
            </div>
            <div>
                {{ field }}
                {{ field.errors }}
            </div>

        {% endfor %}

        <input type="submit" name="submit" class="btn btn-info btn-md" value="Редактирай">
    </form>
{% endblock %}

OnlineQuizPlatform/templates/main/question-delete.html
{% extends 'base.html' %}

{% block content %}
    <div class="delete-category">
    <form class='form' action="{% url 'delete question' question.id %}" method="post">
        <h3 class="text-center text-info">Сигурни ли сте, че искате да изтриете този въпрос?</h3>
        {% csrf_token %}
        {{ form }}
        <input type="submit" name="submit" class="btn btn-info btn-md" value="Изтрий">
    </form>
    </div>

{% endblock %}

OnlineQuizPlatform/templates/main/question_create.html
{% extends 'base.html' %}

{% block content %}
    <form class='form' action="{% url 'create question' %}" method="post">
        <h3 class="text-center text-info">Създай въпрос</h3>
        {% csrf_token %}
        {% for field in form %}
            <div>
                {{ field.label_tag }}
            </div>
            <div>
                {{ field }}
                {{ field.errors }}
            </div>

        {% endfor %}

        <input type="submit" name="submit" class="btn btn-info btn-md" value="Създай">
    </form>
{% endblock %}

OnlineQuizPlatform/templates/main/question_edit.html
{% extends 'base.html' %}

{% block content %}
    <form class='form' action="{% url 'edit question' question.id %}" method="post">
        <h3 class="text-center text-info">Редактирай въпрос</h3>
        {% csrf_token %}
        {% for field in form %}
            <div>
                {{ field.label_tag }}
            </div>
            <div>
                {{ field }}
                {{ field.errors }}
            </div>

        {% endfor %}

        <input type="submit" name="submit" class="btn btn-info btn-md" value="Редактирай">
    </form>
{% endblock %}

OnlineQuizPlatform/templates/main/quiz-delete.html
{% extends 'base.html' %}

{% block content %}
    <div class="delete-category">
    <form class='form' action="{% url 'delete quiz' quiz.id %}" method="post">
        <h3 class="text-center text-info">Сигурни ли сте, че искате да изтриете куиз {{ quiz.title }}?</h3>
        {% csrf_token %}
        {{ form }}

        <input type="submit" name="submit" class="btn btn-info btn-md" value="Изтрий">
    </form>
    </div>

{% endblock %}

OnlineQuizPlatform/templates/main/quiz_create.html
{% extends 'base.html' %}

{% block content %}
    <form class='form' action="{% url 'create quiz' %}" method="post">
        <h3 class="text-center text-info">Създай куиз</h3>
        {% csrf_token %}
        {% for field in form %}
            <div>
                {{ field.label_tag }}
            </div>
            <div>
                {{ field }}
                {{ field.errors }}
            </div>

        {% endfor %}

        <input type="submit" name="submit" class="btn btn-info btn-md" value="Създай">
    </form>
{% endblock %}

OnlineQuizPlatform/templates/main/quiz_details.html
{% extends 'base.html' %}

{% block content %}
    <div class="category-details">
        <h1 class='text-center'>Куиз: {{ quiz.title }}</h1>
        <h5 class="text-center">Подкатегория: {{ quiz.subcategory }}</h5>
        <h5 class="text-center">Категория: {{ quiz.subcategory.category }}</h5>
        <h5 class="text-center">Създаден: {{ quiz.created_on }}</h5>
        <h5 class="text-center">Автор: {{ quiz.author }}</h5>
        <p class="text-center">{{ quiz.description }}</p>

        {% if quiz.author == request.user %}
            <div class="bp3-button-group">
                <a href="{% url 'edit quiz' quiz.id %}" class="btn btn-primary">Редактирай</a>
                <a href="{% url 'delete quiz' quiz.id %}" class="btn btn-danger">Изтрий</a>
            </div>
        {% endif %}

    </div>

    {% if questions %}
        {% if quiz.author == request.user %}
            <h3 class='text-center'>Въпроси</h3>
            {% for question in questions %}
                <h6>{{ question.description }}</h6>
                <div class="form-check">
                    <div class="form-check">
                        <input class="form-check-input" type="radio" name="{{ question.description }}" id="gridRadios1"
                               value="option1">
                        <label class="form-check-label" for="gridRadios1">
                            {{ question.option1 }}
                        </label>
                    </div>
                    <div class="form-check">
                        <input class="form-check-input" type="radio" name="{{ question.description }}" id="gridRadios2"
                               value="option2">
                        <label class="form-check-label" for="gridRadios2">
                            {{ question.option2 }}
                        </label>
                    </div>
                    <div class="form-check">
                        <input class="form-check-input" type="radio" name="{{ question.description }}" id="gridRadios1"
                               value="option3">
                        <label class="form-check-label" for="gridRadios1">
                            {{ question.option3 }}
                        </label>
                    </div>
                    <div class="form-check">
                        <input class="form-check-input" type="radio" name="{{ question.description }}" id="gridRadios2"
                               value="option4">
                        <label class="form-check-label" for="gridRadios2">
                            {{ question.option4 }}
                        </label>
                    </div>
                    <br>
                </div>
                <div class="bp3-button-group">
                    <a href="{% url 'edit question' question.id %}" class="btn btn-primary">Редактирай</a>
                    <a href="{% url 'delete question' question.id %}" class="btn btn-danger">Изтрий</a>
                </div>
            {% endfor %}
        {% else %}
            <div class="take-quiz">
                <div class="bp3-button-group">
                    <a href="{% url 'take quiz' quiz.id %}" class="btn btn-primary">Започни куиз</a>
                </div>
            </div>
        {% endif %}

    {% else %}
        <div class="take-quiz">
            <h3 class='text-center'>Няма създадени въпроси</h3>
        </div>
    {% endif %}
    {% if quiz.author == request.user %}
        <div class="create-category">
            <a href="{% url 'create question' %}" class="btn btn-primary">Създай въпрос</a>
        </div>
    {% endif %}

{% endblock %}

OnlineQuizPlatform/templates/main/quiz_edit.html
{% extends 'base.html' %}

{% block content %}
    <form class='form' action="{% url 'edit quiz' quiz.id %}" method="post">
        <h3 class="text-center text-info">Редактирай куиз</h3>
        {% csrf_token %}
        {% for field in form %}
            <div>
                {{ field.label_tag }}
            </div>
            <div>
                {{ field }}
                {{ field.errors }}
            </div>

        {% endfor %}

        <input type="submit" name="submit" class="btn btn-info btn-md" value="Редактирай">
    </form>
{% endblock %}

OnlineQuizPlatform/templates/main/result.html
{% extends 'base.html' %}

{% block content %}
<div class="container ">

    <div class="card-columns" style="padding: 10px; margin: 32px;">
        <div class="card" style="width: 32rem; border:5px black solid">
            <img class="card-img-top" src="http://kmit.in/emagazine/wp-content/uploads/2018/02/karnataka-results.jpg" alt="Card image cap">
            <div class="card-body">
                {% if best_result %}
                    <h5 class="card-title">Поздравления, {{ player }}</h5>
                    <h5>Вие постигнахте нов рекорд!</h5>
                {% else %}
                    <h5 class="card-title">{{ player }}, Вашият резултат е:</h5>
                {% endif %}
                <h5 class="card-title">Резултат: {{ score }}</h5>
                <p class="card-text">Време: {{ taken_time }} seconds</p>
                <p class="card-text">Верни отговори: {{ correct }}</p>
                <p class="card-text">Грешни отговори: {{ incorrect }}</p>
                <h5>Успех на следващия куиз!</h5>
            </div>
        </div>
    </div>

</div>
{% endblock %}

OnlineQuizPlatform/templates/main/subcategory-delete.html
{% extends 'base.html' %}

{% block content %}
    <div class="delete-category">
    <form class='form' action="{% url 'delete subcategory' subcategory.id %}" method="post">
        <h3 class="text-center text-info">Сигурни ли сте, че искате да изтриете подкатегория {{ subcategory.name }}?</h3>
        {% csrf_token %}
        {{ form }}

        <input type="submit" name="submit" class="btn btn-info btn-md" value="Изтрий">
    </form>
    </div>

{% endblock %}

OnlineQuizPlatform/templates/main/subcategory_details.html
{% extends 'base.html' %}

{% block content %}
<div class="category-details">
    <h1 class='text-center'>{{ subcategory.name }}</h1>
    <img src="{{ subcategory.picture }}" class="category-picture" alt="description">
    <p class="text-center">{{ subcategory.description }}</p>
    {% if perms.main.change_subcategory %}
    <div class="bp3-button-group">
        <a href="{% url 'edit subcategory' subcategory.id %}" class="btn btn-primary">Редактирай</a>
        <a href="{% url 'delete subcategory' subcategory.id %}" class="btn btn-danger">Изтрий</a>
    </div>
    {% endif %}
</div>

    {% if quizzes %}
        <h3 class='text-center'>Куизове</h3>
        <div class="categories">
            <div class="container mb-5">
                <div class="row mb-5">
                    {% for quiz in quizzes %}
                        <div class="subcategory-elem">
                            <div class="card ml-3 mb-3" style="width: 22rem;">
                                <div class="card-body">
                                    <h3 class='text-center'>{{ quiz.title|truncatechars:20 }}</h3>
                                    <p class="text-center">{{ quiz.description|truncatechars:70 }}</p>
                                    <div class='text-center'>{{ quiz.duration }} мин</div>
                                    <a href="{% url 'quiz details' quiz.id %}" class="btn btn-primary">Виж детайли</a>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>


    {% else %}
        <div class="no_subcategories">
            <h3 class='text-center'>Няма активни куизове</h3>
        </div>
    {% endif %}
    {% if perms.main.add_quiz %}
    <div class="create-category">
        <a href="{% url 'create quiz' %}" class="btn btn-primary">Създай куиз</a>
    </div>
    {% endif %}
{% endblock %}